export const ORDER_CREATED = 'ORDER_CREATED';
export const ORDER_PAYMENT_INTENT_CREATED = 'PAYMENT_INTENT_CREATED';
export const ORDER_PAYMENT_REQUIRES_ACTION = 'PAYMENT_REQUIRES_ACTION';
export const ORDER_PAYMENT_PROCESSING = 'PAYMENT_PROCESSING';
export const ORDER_PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED';
export const ORDER_PAYMENT_FAILED = 'PAYMENT_FAILED';
export const ORDER_PAYMENT_INTENT_CANCELLED = 'PAYMENT_INTENT_CANCELLED';
export const ORDER_PROCESSING = 'ORDER_PROCESSING';
export const ORDER_DEPLOYMENT_IN_PROGRESS = 'DEPLOYMENT_IN_PROGRESS';
export const ORDER_COMPLETE = 'ORDER_COMPLETE';
export const STATIC_SITE_GENERATOR_ENDPOINT = 'STATIC_SITE_GENERATOR_ENDPOINT';
export const GENERATOR_SERVICE_CLIENT_SECRET =
  'GENERATOR_SERVICE_CLIENT_SECRET';
export const GENERATOR_SERVICE_CLIENT_ID = 'GENERATOR_SERVICE_CLIENT_ID';
